export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{exports,exports_private,path,aliases}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;

# Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi


# Git bash prompt
if [ -f "$(brew --prefix bash-git-prompt)/share/gitprompt.sh" ]; then
  GIT_PROMPT_THEME=Default
  source "$(brew --prefix bash-git-prompt)/share/gitprompt.sh"
fi


# AWS bash completion
#complete -C aws_completer aws

# The next line updates PATH for the Google Cloud SDK.
#if [ -f '$GOPATH/google-cloud-sdk/path.bash.inc' ]; then source '$GOPATH/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
#if [ -f '$GOPATH/google-cloud-sdk/completion.bash.inc' ]; then source '$GOPATH/google-cloud-sdk/completion.bash.inc'; fi
