export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export JAVA_HOME=$(/usr/libexec/java_home -v 11)
export GITROOT=$HOME/Code/git
export BASH_SILENCE_DEPRECATION_WARNING=1

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{exports_private,aliases}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;

# Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# Git bash prompt
if [ -f "$(brew --prefix bash-git-prompt)/share/gitprompt.sh" ]; then
  GIT_PROMPT_THEME=Default
  source "$(brew --prefix bash-git-prompt)/share/gitprompt.sh"
fi

export PATH=$PATH:$HOME/Code/bin
export PATH=$PATH:$HOME/Code/git/git.corp.adobe.com/mpeterse/scripts
export PATH=$PATH:/usr/local/bin
