export JAVA_HOME=$(/usr/libexec/java_home)
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/Users/moritz/.cargo/bin
export PATH=$PATH:/Applications/IntelliJ\ IDEA.app/Contents/MacOS
export GITROOT="$HOME/Code/git"

source ~/.exports_private
source ~/.aliases

eval "$(/opt/homebrew/bin/brew shellenv)"

# Install pure prompt
autoload -U promptinit; promptinit
prompt pure
