# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
export JAVA_HOME=$(/usr/libexec/java_home)
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export PATH=$PATH:/Applications/IntelliJ\ IDEA\ CE.app/Contents/MacOS

# Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#export ZSH="$HOME/.oh-my-zsh"
#ZSH_THEME="robbyrussell"

# Plugins
#plugins=(
#  brew
#  docker
#  git
#  macos
#)

source ~/.exports_private
source ~/.aliases

eval "$(/opt/homebrew/bin/brew shellenv)"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
