#!/bin/bash

base_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

brew update
brew upgrade

# Java is required by some formulae (e.g. maven), so it is installed explicitly here.
brew cask install --appdir=/Applications java

while read formula
do
    brew install "$formula"
done < $base_dir/brew.list
