#!/bin/bash

formulae=(
    dockutil
    go
    lftp
    maven
    mongodb
    plantuml
    wget
    gnupg
    graphviz
    libpng
    mercurial
    openssl
    tree
    bash-git-prompt
    bash-completion
)

brew install ${formulae[@]}
