#!/bin/bash

brew update
brew upgrade

formulae=(
    bash-completion
    bash-git-prompt
    dockutil
    gnupg
    go
    graphviz
    lftp
    libpng
    maven
    mercurial
    mongodb
    openssl
    plantuml
    tree
    wget
)

brew install ${formulae[@]}
